const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
const state = {
  user: { name:'', email:'', university:'', college:'', phone:'' },
  registered:false,
  verified:false,
  questionApprovals:Array(10).fill(true),
  answers: JSON.parse(localStorage.getItem('contest-answers') || '{}'),
  question: 0,
  submitted:false,
  videoPlayed:false,
  adminTab:'overview'
};

const questions = [
  {axis:'التعريف بالمنتدى',q:'تستضيف المملكة العربية السعودية منتدى الأمم المتحدة العالمي للبيانات عام 2026. ما الوصف الصحيح للحدث؟',opts:['النسخة الرابعة في جدة','النسخة الخامسة في العلا','النسخة السادسة في الرياض','النسخة السابعة في الدمام'],correct:2},
  {axis:'الطريق إلى الرياض',q:'ما الغاية الرئيسة من سلسلة فعاليات «الطريق إلى الرياض»؟',opts:['الترويج لوجهات سياحية جديدة','التمهيد لاستضافة المنتدى وتعزيز حضور المملكة في مجتمع البيانات العالمي','إعداد إحصاءات محلية دون مشاركة دولية','تنظيم برامج تدريب وظيفي فقط'],correct:1},
  {axis:'تمكين الشباب',q:'أي نتيجة تنسجم مع هدف إشراك طلاب الجامعات في فعاليات الطريق إلى الرياض؟',opts:['تمكين الشباب من قيادة الابتكار في المجال الإحصائي','حصر النقاشات في الخبراء الدوليين','تقليل مشاركة المؤسسات الأكاديمية','فصل التعليم الجامعي عن العمل الإحصائي'],correct:0},
  {axis:'الابتكار والتقنيات',q:'كيف يمكن للتقنيات والمنهجيات المتقدمة أن تعزز الأنظمة الإحصائية؟',opts:['بإلغاء الحاجة إلى التحقق من الجودة','بتطوير جمع البيانات ومعالجتها وتحسين كفاءة إنتاج الإحصاءات','باستبدال جميع المصادر الرسمية بمصادر غير موثقة','بحصر البيانات في شكل واحد ثابت'],correct:1},
  {axis:'الشراكات والتعاون',q:'أي ممارسة تعبّر بصورة أفضل عن تعزيز الشراكات في مجال البيانات؟',opts:['عمل كل جهة بمعزل عن الجهات الأخرى','تبادل المعرفة وبناء القدرات والتعاون بين القطاعات','منع مشاركة الخبرات الإحصائية','قصر استخدام البيانات على الجهة المنتجة'],correct:1},
  {axis:'الأثر الاجتماعي',q:'ما الاستخدام الأكثر ارتباطًا بتوظيف البيانات لتحقيق أثر اجتماعي ونمو شامل؟',opts:['دعم السياسات والقرارات بأدلة موثوقة تراعي احتياجات المجتمع','زيادة حجم البيانات دون تحديد غرض','نشر المؤشرات دون تفسيرها','الاعتماد على الانطباعات بدل الأدلة'],correct:0},
  {axis:'الشمول والعدالة',q:'ما السمة الأساسية لنظام بيانات شامل وعادل؟',opts:['تمثيل فئة واحدة من المجتمع','إتاحة النتائج دون حماية الأفراد','تمثيل مختلف فئات المجتمع وتقليل فجوات البيانات','جمع أكبر قدر من البيانات بصرف النظر عن الحاجة'],correct:2},
  {axis:'حوكمة وأخلاقيات البيانات',q:'أي إجراء يحقق التوازن بين الاستفادة من البيانات وحماية الأفراد؟',opts:['نشر البيانات الشخصية كاملة','تطبيق الحوكمة وحماية الخصوصية وتحديد صلاحيات الوصول','إلغاء ضوابط مشاركة البيانات','إتاحة البيانات الحساسة لجميع المستخدمين'],correct:1},
  {axis:'البيانات والاستدامة',q:'كيف تدعم البيانات الإحصائية تحقيق مستقبل مستدام؟',opts:['بقياس التقدم وتحديد التحديات وتوجيه السياسات نحو أهداف التنمية المستدامة','بالتركيز على النتائج قصيرة المدى فقط','باستبعاد المؤشرات البيئية والاجتماعية','بمنع المقارنة بين الفترات الزمنية'],correct:0},
  {axis:'جودة الإحصاءات وصنع القرار',q:'لماذا تُعد جودة البيانات الإحصائية عنصرًا أساسيًا في صنع القرار؟',opts:['لأنها تزيد عدد التقارير فقط','لأنها تضمن أن تكون القرارات مبنية على معلومات دقيقة وموثوقة وفي الوقت المناسب','لأنها تلغي الحاجة إلى تحليل النتائج','لأنها تمنع تحديث المؤشرات مستقبلًا'],correct:1}
];

const participants = [
 ['سارة العتيبي','جامعة الملك سعود','95','08:42','مكتمل'],['عبدالله القحطاني','جامعة الإمام','95','09:11','مكتمل'],['نورة الحربي','جامعة الأميرة نورة','92','07:58','مكتمل'],['محمد الزهراني','جامعة الملك عبدالعزيز','90','08:16','مكتمل'],['ريم الدوسري','جامعة القصيم','88','09:44','مكتمل'],['فيصل الشهري','جامعة الملك خالد','—','—','قيد التقدم']
];

const saudiUniversities = [
  'الجامعة الإسلامية','جامعة أم القرى','جامعة الإمام محمد بن سعود الإسلامية','جامعة الإمام عبدالرحمن بن فيصل',
  'جامعة الأمير سطام بن عبدالعزيز','جامعة الأميرة نورة بنت عبدالرحمن','جامعة الباحة','جامعة الجوف',
  'جامعة الحدود الشمالية','جامعة الطائف','جامعة القصيم','جامعة المجمعة','جامعة الملك خالد','جامعة الملك سعود',
  'جامعة الملك عبدالعزيز','جامعة الملك فيصل','جامعة الملك فهد للبترول والمعادن','جامعة الملك سعود بن عبدالعزيز للعلوم الصحية',
  'جامعة بيشة','جامعة تبوك','جامعة جازان','جامعة جدة','جامعة حائل','جامعة حفر الباطن','جامعة شقراء','جامعة طيبة',
  'جامعة نجران','الجامعة السعودية الإلكترونية','جامعة الملك عبدالله للعلوم والتقنية','الجامعة العربية المفتوحة',
  'جامعة الأمير سلطان','جامعة الأمير محمد بن فهد','جامعة الأمير مقرن بن عبدالعزيز','جامعة الفيصل','جامعة اليمامة',
  'جامعة عفت','جامعة دار الحكمة','جامعة دار العلوم','جامعة الأعمال والتكنولوجيا','جامعة المعرفة',
  'جامعة رياض العلم','جامعة سليمان الراجحي','جامعة فهد بن سلطان','جامعة المستقبل'
].sort((a,b)=>a.localeCompare(b,'ar'));

function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function steps(active){return `<div class="stepper">${[1,2,3,4].map((n,i)=>`${i?`<span class="step-line ${n<=active?'done':''}"></span>`:''}<span class="step-dot ${n<active?'done':n===active?'active':''}">${n<active?'✓':n}</span>`).join('')}</div>`}
function go(page){window.scrollTo({top:0,behavior:'smooth'});if(page==='admin'&&sessionStorage.getItem('admin-authorized')!=='yes'){adminLogin();return}if(['material','quiz','review','success'].includes(page)&&!state.verified){showToast('أكمل التسجيل والتحقق من البريد أولًا');routes[state.registered?'verify':'register']();return}if(page==='material')page='quiz';routes[page]?.();if(page==='quiz')document.querySelector('.question .eyebrow').textContent=`محور ${questions[state.question].axis}`;if(page==='instructions'){[...document.querySelectorAll('.info-box')].find(el=>el.textContent.includes('تُرتب النتائج'))?.remove();if(!state.registered)document.querySelector('.stepper')?.remove();}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-go]');if(el){e.preventDefault();go(el.dataset.go)}});
document.querySelector('.mobile-menu')?.addEventListener('click',e=>{const nav=document.querySelector('.main-nav');const open=nav.classList.toggle('mobile-open');e.currentTarget.textContent=open?'×':'☰';e.currentTarget.setAttribute('aria-expanded',String(open));});
document.querySelector('.main-nav')?.addEventListener('click',()=>{if(innerWidth<=820){document.querySelector('.main-nav').classList.remove('mobile-open');document.querySelector('.mobile-menu').textContent='☰';}});
document.addEventListener('click',e=>{const approve=e.target.closest('[data-approve-q]');if(approve){state.questionApprovals[+approve.dataset.approveQ]=true;admin();showToast('تم اعتماد السؤال')}if(e.target.closest('#approveAll')){state.questionApprovals.fill(true);admin();showToast('تم اعتماد جميع الأسئلة')}});

function home(){app.innerHTML=`<div class="home-stack"><section class="card hero"><div><span class="eyebrow">الرياض · نوفمبر 2026</span><h1>مبادرة تمثيل الطلاب في<br><em>المنتدى العالمي للبيانات</em></h1><p class="lead">فرصة لطلاب الجامعات للمشاركة في منتدى الأمم المتحدة العالمي السادس للبيانات، وإبراز طموح الشباب السعودي في البيانات والإحصاء والابتكار.</p><div class="actions"><button class="btn btn-primary" data-go="register">قدّم الآن ←</button><button class="btn btn-secondary" data-go="instructions">آلية المشاركة</button></div></div><aside class="hero-panel"><h3>عن المنتدى</h3><div class="facts"><div class="fact"><strong>السادس</strong><span>نسخة المنتدى</span></div><div class="fact"><strong>الرياض</strong><span>المدينة المستضيفة</span></div><div class="fact"><strong>نوفمبر</strong><span>موعد الاستضافة</span></div><div class="fact"><strong>2026</strong><span>عام المنتدى</span></div></div><div class="prize"><span>الفرصة</span><strong>تمثيل الطلاب</strong></div></aside></section><section class="forum-info"><div class="forum-copy"><span class="eyebrow">الطريق إلى الرياض 2026</span><h2>بيانات أفضل لمستقبل أكثر استدامة</h2><p>«الطريق إلى الرياض» سلسلة متكاملة من الفعاليات لترسيخ الحضور السعودي في مجال البيانات، وإبراز التحول الإحصائي الذي تشهده المملكة، وتعزيز التعاون الدولي والحوار حول دور البيانات في التنمية المستدامة.</p></div><div class="theme-grid"><article><b>01</b><strong>الابتكار والتقنيات المتقدمة</strong><span>توظيف التقنيات والمنهجيات الحديثة لتطوير الأنظمة الإحصائية.</span></article><article><b>02</b><strong>الأثر الاجتماعي والنمو الشامل</strong><span>استخدام البيانات الموثوقة لدعم السياسات وصنع القرار.</span></article><article><b>03</b><strong>الشراكات والتعاون</strong><span>بناء القدرات وتبادل المعرفة بين القطاعات والمجتمع الدولي.</span></article><article><b>04</b><strong>البيانات والاستدامة</strong><span>تسخير البيانات لخدمة مستقبل مستدام وتحقيق أهداف التنمية.</span></article></div><a class="source-link" href="https://www.stats.gov.sa/ar/united-nations-world-data-forum" target="_blank" rel="noopener">زيارة صفحة المنتدى الرسمية ↗</a></section></div>`}

function register(){app.innerHTML=`<section class="card narrow">${steps(1)}<div class="step-head"><span class="status-pill">الخطوة الأولى</span><h2>أنشئ مشاركتك</h2><p>استخدم بريدك الجامعي للتأكد من أهليتك</p></div><form id="regForm"><div class="form-grid"><div class="field"><label>الاسم الثلاثي</label><input name="name" required placeholder="مثال: سارة أحمد العتيبي" value="${state.user.name}"></div><div class="field"><label>البريد الجامعي</label><input name="email" type="email" required placeholder="name@university.edu.sa" value="${state.user.email}"><div class="hint">يجب أن ينتهي النطاق بـ edu.sa</div></div><div class="field"><label>الجامعة</label><select name="university"><option>جامعة الملك سعود</option><option>جامعة الإمام محمد بن سعود</option><option>جامعة الملك عبدالعزيز</option><option>جامعة الأميرة نورة</option><option>جامعة الملك خالد</option></select></div><div class="field"><label>الكلية / التخصص</label><input name="college" required placeholder="مثال: كلية علوم الحاسب"></div><div class="field full"><label>رقم الجوال</label><input name="phone" required placeholder="05xxxxxxxx" inputmode="tel"></div><label class="check field full"><input type="checkbox" required><span>أوافق على شروط المسابقة وسياسة الخصوصية، وأقر بصحة البيانات المدخلة.</span></label></div><div class="form-actions"><button type="button" class="btn btn-secondary" data-go="home">رجوع</button><button class="btn btn-primary">إرسال رمز التحقق</button></div></form></section>`;
document.querySelector('input[name="name"]').placeholder='مثال: عبدالعزيز محمد الغامدي';
const universitySelect=document.querySelector('select[name="university"]');
universitySelect.outerHTML=`<div class="university-picker"><div class="university-input-wrap"><input id="universitySearch" name="university" required autocomplete="off" placeholder="ابحث عن جامعتك" value="${state.user.university||''}" aria-expanded="false" aria-controls="universityOptions"><span class="picker-arrow">⌄</span></div><div id="universityOptions" class="university-options" hidden></div></div><div class="hint">اكتب جزءًا من اسم الجامعة أو اختر من القائمة</div>`;
const universityInput=document.querySelector('#universitySearch'),universityOptions=document.querySelector('#universityOptions');
const renderUniversities=(query='')=>{const normalized=query.trim();const matches=saudiUniversities.filter(name=>name.includes(normalized));universityOptions.innerHTML=matches.length?matches.map(name=>`<button type="button" class="university-option" data-university="${name}">${name}</button>`).join(''):`<div class="university-empty">لا توجد جامعة مطابقة</div>`;};
const openUniversities=()=>{renderUniversities(universityInput.value);universityOptions.hidden=false;universityInput.setAttribute('aria-expanded','true');};
const closeUniversities=()=>{universityOptions.hidden=true;universityInput.setAttribute('aria-expanded','false');};
universityInput.addEventListener('focus',openUniversities);universityInput.addEventListener('click',openUniversities);universityInput.addEventListener('input',openUniversities);
universityOptions.addEventListener('click',e=>{const option=e.target.closest('[data-university]');if(!option)return;universityInput.value=option.dataset.university;closeUniversities();});
document.addEventListener('click',e=>{if(!e.target.closest('.university-picker'))closeUniversities();});
document.querySelector('#regForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!/edu\.sa$/i.test(d.email)){showToast('يرجى استخدام بريد جامعي ينتهي بـ edu.sa');return}Object.assign(state.user,d);state.registered=true;go('verify')};}

function verify(){app.innerHTML=`<section class="card narrow">${steps(2)}<div class="step-head"><span class="status-pill">تحقق من البريد</span><h2>أدخل رمز التحقق</h2><p>أرسلنا رمزًا من 6 أرقام إلى <b>${state.user.email||'student@ksu.edu.sa'}</b></p></div><div class="otp">${[0,1,2,3,4,5].map(i=>`<input maxlength="1" inputmode="numeric" aria-label="الرقم ${i+1}">`).join('')}</div><div class="info-box">للتجربة: أدخل أي ستة أرقام. صلاحية الرمز 04:32 دقائق.</div><div class="form-actions"><button class="btn btn-secondary" data-go="register">تعديل البريد</button><button id="verifyBtn" class="btn btn-primary" disabled>تحقق ومتابعة</button></div><p class="skip">لم يصلك الرمز؟ <button id="resend" class="edit-link">إعادة الإرسال</button></p></section>`;
const inputs=[...document.querySelectorAll('.otp input')];inputs.forEach((inp,i)=>inp.oninput=()=>{inp.value=inp.value.replace(/\D/g,'');if(inp.value&&i<5)inputs[i+1].focus();document.querySelector('#verifyBtn').disabled=!inputs.every(x=>x.value)});document.querySelector('#verifyBtn').onclick=()=>{state.verified=true;go('quiz')};document.querySelector('#resend').onclick=()=>showToast('تم إرسال رمز جديد');inputs[0].focus();}

function instructions(){app.innerHTML=`<section class="card narrow">${steps(3)}<div class="step-head"><span class="status-pill">قبل أن تبدأ</span><h2>تعليمات المسابقة</h2><p>اقرأها جيدًا لضمان تجربة عادلة وسلسة</p></div><div class="instructions"><div class="instruction"><b>01</b><div><strong>10 أسئلة</strong><span>سؤال واحد في كل شاشة، ويمكنك التنقل بينها.</span></div></div><div class="instruction"><b>02</b><div><strong>10 دقائق</strong><span>يبدأ الوقت عند الضغط على بدء المسابقة.</span></div></div><div class="instruction"><b>03</b><div><strong>محاولة واحدة</strong><span>لا يمكن تعديل الإجابات بعد الإرسال النهائي.</span></div></div><div class="instruction"><b>04</b><div><strong>حفظ تلقائي</strong><span>تُحفظ إجابتك تلقائيًا على هذا الجهاز.</span></div></div></div><div class="info-box">تُرتب النتائج حسب أعلى درجة. عند تساوي الدرجات، يُجرى سحب إلكتروني موثق بين أصحاب الدرجة نفسها.</div><div class="form-actions"><button class="btn btn-secondary" data-go="home">رجوع</button><button class="btn btn-primary" data-go="material">متابعة</button></div></section>`}

function material(){app.innerHTML=`<section class="card narrow">${steps(4)}<div class="step-head"><span class="status-pill">مادة تعريفية · اختيارية</span><h2>الابتكار الذي يصنع الفرق</h2><p>فيديو تعريفي قصير يساعدك على الاستعداد</p></div><div class="video" id="video"><div class="video-copy"><button class="play" aria-label="تشغيل">▶</button><h3>مدخل إلى الابتكار والاستدامة</h3><p>مدة الفيديو 02:14 دقيقة</p></div></div><div class="form-actions"><button class="btn btn-secondary" data-go="instructions">رجوع</button><button class="btn btn-primary" data-go="quiz">ابدأ المسابقة</button></div><div class="skip">يمكنك تخطي المادة والبدء مباشرة</div></section>`;document.querySelector('.play').onclick=()=>{state.videoPlayed=true;document.querySelector('.video-copy').innerHTML='<h3>تمت مشاهدة المادة ✓</h3><p>أصبحت جاهزًا لبدء المسابقة</p>';showToast('اكتملت المادة التعريفية')};}

function quiz(){const i=state.question,q=questions[i];app.innerHTML=`<section class="quiz-layout"><div class="card question"><div class="quiz-top"><span>السؤال <b>${i+1}</b> من ${questions.length}</span><span><span class="autosave">✓ تم الحفظ تلقائيًا</span> · ⏱ <b>08:42</b></span></div><div class="progress-track"><div class="progress-bar" style="width:${(i+1)*10}%"></div></div><small class="eyebrow">محور الابتكار والاستدامة</small><h2>${q.q}</h2><div class="options">${q.opts.map((o,n)=>`<div class="option ${state.answers[i]==n?'selected':''}" data-answer="${n}"><span class="radio"></span><span>${o}</span></div>`).join('')}</div><div class="form-actions"><button class="btn btn-secondary" id="prev" ${i===0?'disabled':''}>السابق</button><button class="btn btn-primary" id="next">${i===questions.length-1?'مراجعة الإجابات':'التالي'}</button></div></div><aside class="card q-nav"><h3>الأسئلة</h3><div class="q-grid">${questions.map((_,n)=>`<button class="q-num ${state.answers[n]!==undefined?'answered':''} ${n===i?'current':''}" data-q="${n}">${n+1}</button>`).join('')}</div><div class="legend"><i></i> تمت الإجابة · اضغط رقمًا للانتقال</div></aside></section>`;
document.querySelectorAll('[data-answer]').forEach(el=>el.onclick=()=>{state.answers[i]=+el.dataset.answer;localStorage.setItem('contest-answers',JSON.stringify(state.answers));document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const s=document.querySelector('.autosave');s.classList.add('show');setTimeout(()=>s.classList.remove('show'),1400)});document.querySelectorAll('[data-q]').forEach(el=>el.onclick=()=>{state.question=+el.dataset.q;quiz()});document.querySelector('#prev').onclick=()=>{state.question--;quiz()};document.querySelector('#next').onclick=()=>{if(i===questions.length-1)go('review');else{state.question++;quiz()}};}

function review(){const answered=Object.keys(state.answers).length;app.innerHTML=`<section class="card narrow"><div class="step-head"><span class="status-pill">المراجعة النهائية</span><h2>راجع إجاباتك</h2><p>أجبت عن ${answered} من ${questions.length} أسئلة</p></div>${answered<questions.length?`<div class="info-box">تبقى ${questions.length-answered} سؤال/أسئلة دون إجابة. يمكنك الإرسال أو العودة لإكمالها.</div>`:''}<div class="review-list">${questions.map((q,i)=>`<div class="review-row"><b>${i+1}</b><div><small>${q.q}</small><strong>${state.answers[i]!==undefined?q.opts[state.answers[i]]:'لم تتم الإجابة'}</strong></div><button class="edit-link" data-edit="${i}">تعديل</button></div>`).join('')}</div><label class="check"><input id="confirm" type="checkbox"><span>أؤكد أنني راجعت إجاباتي وأرغب في إرسال المشاركة نهائيًا.</span></label><div class="form-actions"><button class="btn btn-secondary" data-go="quiz">العودة للأسئلة</button><button id="submitFinal" class="btn btn-primary" disabled>إرسال المشاركة</button></div></section>`;document.querySelectorAll('[data-edit]').forEach(el=>el.onclick=()=>{state.question=+el.dataset.edit;quiz()});const c=document.querySelector('#confirm'),b=document.querySelector('#submitFinal');c.onchange=()=>b.disabled=!c.checked;b.onclick=()=>{state.submitted=true;localStorage.removeItem('contest-answers');go('success')}}

function success(){app.innerHTML=`<section class="card narrow success"><div class="success-icon">✓</div><span class="status-pill">تم استلام مشاركتك</span><h2>شكرًا لمشاركتك${state.user.name?'، '+state.user.name.split(' ')[0]:''}!</h2><p class="lead" style="margin:auto">سنعتمد النتائج بعد انتهاء المبادرة، وسيصلك إشعار عبر بريدك الجامعي.</p><div class="actions" style="justify-content:center"><button class="btn btn-primary" data-go="home">العودة للرئيسية</button><button class="btn btn-secondary" data-go="admin">عرض لوحة الإدارة</button></div></section>`}

function admin(){const content={overview:adminOverview,participants:adminParticipants,questions:adminQuestions,results:adminResults,draw:adminDraw}[state.adminTab]();app.innerHTML=`<section class="admin-shell"><aside class="admin-side"><h2>إدارة المبادرة</h2>${[['overview','نظرة عامة'],['participants','المشاركون'],['questions','الأسئلة'],['results','النتائج'],['draw','السحب الإلكتروني']].map(([k,l])=>`<button class="admin-tab ${state.adminTab===k?'active':''}" data-admin="${k}">${l}</button>`).join('')}</aside><div class="admin-main"><div class="admin-head"><div><h1>${({overview:'نظرة عامة',participants:'المشاركون',questions:'بنك الأسئلة',results:'النتائج والترتيب',draw:'السحب الإلكتروني'})[state.adminTab]}</h1><p>مبادرة تمثيل الطلاب في المنتدى العالمي للبيانات · 2026</p></div><div class="avatar">م ع</div></div>${content}</div></section>`;document.querySelectorAll('[data-admin]').forEach(el=>el.onclick=()=>{state.adminTab=el.dataset.admin;admin()});if(state.adminTab==='draw')setupDraw();}
function adminOverview(){return `<div class="metrics"><div class="card metric"><span>إجمالي المسجلين</span><strong>1,248</strong><small>↑ 12% هذا الأسبوع</small></div><div class="card metric"><span>مشاركات مكتملة</span><strong>986</strong><small>معدل الإكمال 79%</small></div><div class="card metric"><span>متوسط الدرجات</span><strong>78%</strong><small>+3 نقاط</small></div><div class="card metric"><span>جامعات مشاركة</span><strong>48</strong><small>من 13 منطقة</small></div></div><div class="card panel"><div class="panel-head"><h3>أحدث المشاركات</h3><button class="edit-link" data-admin="participants">عرض الكل</button></div>${participantTable(participants.slice(0,5))}</div>`}
function participantTable(rows){return `<div class="table-wrap"><table><thead><tr><th>المشارك</th><th>الجامعة</th><th>الدرجة</th><th>المدة</th><th>الحالة</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="tag ${r[4]==='قيد التقدم'?'gold':''}">${r[4]}</span></td></tr>`).join('')}</tbody></table></div>`}
function adminParticipants(){return `<div class="card panel"><div class="panel-head"><h3>جميع المشاركين (${participants.length})</h3><button class="btn btn-secondary" id="export">تصدير CSV</button></div><div class="tabs"><button class="mini-tab active">الكل</button><button class="mini-tab">مكتمل</button><button class="mini-tab">قيد التقدم</button></div>${participantTable(participants)}</div>`}
function adminQuestions(){return `<div class="card panel"><div class="panel-head"><h3>الأسئلة المنشورة</h3><button class="btn btn-primary" id="addQ">+ إضافة سؤال</button></div><div class="review-list">${questions.map((q,i)=>`<div class="review-row"><b>${i+1}</b><div><strong>${q.q}</strong><small>اختيار من متعدد · ${q.opts.length} خيارات</small></div><button class="edit-link">تعديل</button></div>`).join('')}</div></div>`}
function adminResults(){return `<div class="metrics"><div class="card metric"><span>أعلى درجة</span><strong>95%</strong><small>مشاركان متساويان</small></div><div class="card metric"><span>درجة التأهل</span><strong>85%</strong><small>أفضل 10%</small></div><div class="card metric"><span>نتائج معتمدة</span><strong>986</strong><small>100% مكتملة</small></div><div class="card metric"><span>موعد الإعلان</span><strong style="font-size:20px">5 أكتوبر</strong><small>2026</small></div></div><div class="card panel"><div class="panel-head"><h3>الترتيب النهائي</h3><button class="btn btn-primary" data-admin="draw">إجراء السحب للمتساوين</button></div>${participantTable(participants.slice(0,5))}</div>`}
function adminDraw(){return `<div class="card panel"><div class="draw-box"><span class="status-pill">تعادل في المركز الأول</span><h2>السحب الإلكتروني الموثّق</h2><p>سيتم الاختيار عشوائيًا بين المشاركين المتساويين بدرجة 95%، مع تسجيل وقت ونتيجة السحب.</p><div class="draw-candidates"><div class="candidate" data-candidate>سارة العتيبي<br><small>95% · 08:42</small></div><div class="candidate" data-candidate>عبدالله القحطاني<br><small>95% · 09:11</small></div></div><button id="drawBtn" class="btn" style="background:var(--gold);color:#30250f">بدء السحب العشوائي</button><div id="drawLog" style="margin-top:18px;font-size:12px;opacity:.75">لم يتم إجراء السحب بعد</div></div></div>`}
function setupDraw(){document.querySelector('#drawBtn').onclick=()=>{const cs=[...document.querySelectorAll('[data-candidate]')],btn=document.querySelector('#drawBtn');btn.disabled=true;let n=0;const t=setInterval(()=>{cs.forEach(x=>x.classList.remove('winner'));cs[n%2].classList.add('winner');n++;if(n===9){clearInterval(t);cs.forEach(x=>x.classList.remove('winner'));cs[0].classList.add('winner');btn.textContent='تم اعتماد الفائزة: سارة العتيبي';document.querySelector('#drawLog').textContent='رقم السحب DR-2026-004 · 5 أغسطس 2026، 14:30 · الحالة: موثّق';showToast('تم توثيق نتيجة السحب بنجاح')}},180)}}

function adminLogin(){app.innerHTML=`<section class="card narrow admin-login"><div class="lock-icon">🔒</div><div class="step-head"><span class="status-pill">منطقة مخصصة</span><h2>الدخول إلى لوحة الإدارة</h2><p>أدخل الرقم السري للمتابعة</p></div><form id="adminLoginForm"><div class="field"><label for="adminPin">الرقم السري</label><input id="adminPin" type="password" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="••••" required></div><div id="pinError" class="pin-error" hidden>الرقم السري غير صحيح، حاول مرة أخرى.</div><div class="form-actions"><button type="button" class="btn btn-secondary" data-go="home">رجوع</button><button class="btn btn-primary">دخول</button></div></form></section>`;const form=document.querySelector('#adminLoginForm'),pin=document.querySelector('#adminPin'),error=document.querySelector('#pinError');form.onsubmit=e=>{e.preventDefault();if(pin.value==='1406'){sessionStorage.setItem('admin-authorized','yes');admin();showToast('تم تسجيل الدخول بنجاح')}else{error.hidden=false;pin.value='';pin.focus();}};pin.focus();}

const renderQuiz=quiz;quiz=function(){renderQuiz();const label=document.querySelector('.question .eyebrow');if(label)label.textContent=`محور ${questions[state.question].axis}`;};
adminQuestions=function(){const approved=state.questionApprovals.filter(Boolean).length;return `<div class="approval-summary"><div><span>حالة اعتماد اللجنة</span><strong>${approved} من ${questions.length} أسئلة معتمدة</strong></div><div class="approval-progress"><i style="width:${approved/questions.length*100}%"></i></div><button id="approveAll" class="btn btn-primary" ${approved===questions.length?'disabled':''}>✓ اعتماد جميع الأسئلة</button></div><div class="card panel"><div class="panel-head"><h3>الأسئلة والمحاور</h3><span class="tag ${approved===questions.length?'':'gold'}">${approved===questions.length?'جاهزة للنشر':'بانتظار الاعتماد'}</span></div><div class="review-list">${questions.map((q,i)=>`<div class="review-row approval-row"><b>${i+1}</b><div><small>محور ${q.axis}</small><strong>${q.q}</strong><span class="correct-answer">الإجابة الصحيحة: ${q.opts[q.correct]}</span></div>${state.questionApprovals[i]?`<span class="approved-mark">✓ معتمد</span>`:`<button class="btn approve-btn" data-approve-q="${i}">اعتماد</button>`}</div>`).join('')}</div></div>`;};
function homeWithLogo(){home();const target=document.querySelector('.hero>div');const logo=document.querySelector('#forumLogoTemplate')?.content.cloneNode(true);if(target&&logo)target.prepend(logo);}
const routes={home:homeWithLogo,register,verify,instructions,material,quiz,review,success,admin};
homeWithLogo();
